apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-envvars
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  # IPA-specific environment variables
  {{- range $key, $value := .Values.envvars }}
  {{ $key }}: {{ $value }}
  {{- end }}
