ipa:
  # Where to mount (inside the containers) the k8s job templates
  config_dir_templates: "/etc/k8s_jinja_templates"
  # Set to false if for some reason you don't want to create RBAC rules (unlikely)
  create_rbac: true
  # Virtual environment command
  venv_activate_cmd: "source /virtualenvs/ipa/bin/activate"
  # Image pull policy [Always, IfNotPresent]
  image_pull_policy: "IfNotPresent"
  # Service account
  service_account: "workload-sa"
  # Pipelines to include - leave as null to include everything, otherwise it's a list of strings
  include_published_pipelines: null
  # Name of module holding custom endpoints code - if null/not specified, no custom endpoints
  custom_endpoints_module: null
  # Enable kubetail
  enable_kubetail: false
  # Horizontal Pod autoscaler
  horizontal_autoscaler_envs:
    dev:
      min_replicas: 1
      max_replicas: 1
      avg_cpu: 50
      avg_memory: 50
    stg:
      min_replicas: 1
      max_replicas: 5
      avg_cpu: 50
      avg_memory: 50
    prod:
      min_replicas: 1
      max_replicas: 5
      avg_cpu: 50
      avg_memory: 50
  # Requested resources and limits
  resources:
    dev:
      requests:
        memory: "384Mi"
        cpu: "100m"
      limits:
        memory: "1Gi"
        cpu: "1"
    stg:
      requests:
        memory: "384Mi"
        cpu: "100m"
      limits:
        memory: "1Gi"
        cpu: "1"
    prod:
      requests:
        memory: "384Mi"
        cpu: "100m"
      limits:
        memory: "1Gi"
        cpu: "1"

istio:
  # String executing the command that waits for Istio to be up
  wait_for_istio: "/etc/istio_scripts/wait-for-istio.sh"
  # String executing the command to execute to quit Istio
  quit_istio: "/etc/istio_scripts/quit-istio.sh"

init:

  # Override this from the cmdline
  gcloud: {}
  # Override this from the cmdline - --set init.azure....
  azure: {}
  # Override this from the cmdline
  databricks: {}

envvars:
  # add custom environment variables
